// ============================================================================
// CHRONOS - Data-Driven Time-of-Day & Weather Orchestration System
// ChronosTypes.h - Shared enums and structs
// NOTE: Replace CHRONOS_API with YOUR project's module API macro
// (the one you see in any header generated by your project, e.g. MYPROJECT_API)
// ============================================================================
#pragma once

#include "CoreMinimal.h"
#include "ChronosTypes.generated.h"

class UChronosWeatherPreset;

UENUM(BlueprintType)
enum class EPrecipitationType : uint8
{
	None	UMETA(DisplayName = "None"),
	Rain	UMETA(DisplayName = "Rain"),
	Snow	UMETA(DisplayName = "Snow")
};

// Per-level time/sun configuration, edited on the Director actor instance.
USTRUCT(BlueprintType)
struct FChronosSettings
{
	GENERATED_BODY()

	/** Hour the clock starts at [0..24) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chronos|Time", meta = (ClampMin = "0.0", ClampMax = "24.0"))
	float StartHour = 9.f;

	/** Game-seconds advanced per real second. 60 = a full day in 24 real minutes. 0 = paused. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chronos|Time", meta = (ClampMin = "0.0"))
	float TimeScale = 60.f;

	/** Highest sun angle at solar noon, in degrees. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chronos|Sun", meta = (ClampMin = "5.0", ClampMax = "90.0"))
	float MaxSunElevation = 65.f;

	/** Rotates the whole sun path. 90 makes the sun rise due +Y. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chronos|Sun")
	float AzimuthOffset = 0.f;
};

// Fully evaluated, blended set of scene values. This is what the Director
// applies to lights/fog and what gameplay reads. Never holds asset pointers.
USTRUCT(BlueprintType)
struct FWeatherSnapshot
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly, Category = "Chronos") float SunIntensity = 10.f;
	UPROPERTY(BlueprintReadOnly, Category = "Chronos") float SunColorTemperature = 6500.f;
	UPROPERTY(BlueprintReadOnly, Category = "Chronos") FLinearColor SunTint = FLinearColor::White;
	UPROPERTY(BlueprintReadOnly, Category = "Chronos") float MoonlightIntensity = 0.05f;
	UPROPERTY(BlueprintReadOnly, Category = "Chronos") float SkyLightIntensity = 1.f;
	UPROPERTY(BlueprintReadOnly, Category = "Chronos") float FogDensity = 0.02f;
	UPROPERTY(BlueprintReadOnly, Category = "Chronos") float FogHeightFalloff = 0.2f;
	UPROPERTY(BlueprintReadOnly, Category = "Chronos") float CloudCoverage = 0.f;
	UPROPERTY(BlueprintReadOnly, Category = "Chronos") float WindSpeed = 2.f;
	UPROPERTY(BlueprintReadOnly, Category = "Chronos") EPrecipitationType Precipitation = EPrecipitationType::None;
	UPROPERTY(BlueprintReadOnly, Category = "Chronos") float PrecipitationIntensity = 0.f;

	/** Linear-interpolates every scalar field. */
	static FWeatherSnapshot Lerp(const FWeatherSnapshot& A, const FWeatherSnapshot& B, float Alpha)
	{
		FWeatherSnapshot R;
		R.SunIntensity          = FMath::Lerp(A.SunIntensity, B.SunIntensity, Alpha);
		R.SunColorTemperature   = FMath::Lerp(A.SunColorTemperature, B.SunColorTemperature, Alpha);
		R.SunTint               = FLinearColor::LerpUsingHSV(A.SunTint, B.SunTint, Alpha);
		R.MoonlightIntensity    = FMath::Lerp(A.MoonlightIntensity, B.MoonlightIntensity, Alpha);
		R.SkyLightIntensity     = FMath::Lerp(A.SkyLightIntensity, B.SkyLightIntensity, Alpha);
		R.FogDensity            = FMath::Lerp(A.FogDensity, B.FogDensity, Alpha);
		R.FogHeightFalloff      = FMath::Lerp(A.FogHeightFalloff, B.FogHeightFalloff, Alpha);
		R.CloudCoverage         = FMath::Lerp(A.CloudCoverage, B.CloudCoverage, Alpha);
		R.WindSpeed             = FMath::Lerp(A.WindSpeed, B.WindSpeed, Alpha);
		R.PrecipitationIntensity= FMath::Lerp(A.PrecipitationIntensity, B.PrecipitationIntensity, Alpha);
		// Discrete state: switch past the halfway point of the blend.
		R.Precipitation         = (Alpha < 0.5f) ? A.Precipitation : B.Precipitation;
		return R;
	}
};
